# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42904d5a09aedd54b77ac38a76f4e3b49859183a4897351a674db0036c546e1512a72abfb5598c7b04f1f41590def94bc400ed278239d157ce67bbba544fc06a

test:
  secret_key_base: 8000a15b365c1987601aad575c34459e91674b797d861211eb164c993e3e8a8a216e0d6f0ec016e8d54d7c1510c926fdb1ba6d447cf0462c595e1708445d27f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
